# -*- coding: utf-8 -*-
"""youtube_to_mfcc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ciIlWetlXzteCQVhpOPCQ6kcBYyaeo-r
"""

import os
os.listdir()

!pip install yt-dlp librosa soundfile tqdm

import os

os.makedirs("audio_data/english", exist_ok=True)
os.makedirs("audio_data/bangla", exist_ok=True)

english_urls = [
    "https://youtu.be/4_zKjSIPd6U?si=S5H-PXXlt1Ts2j-b",
    "https://youtu.be/5zNrdbFn-J4?si=dtqmL4atG1X1pmIm",
    "https://youtu.be/IE9YmOprijk?si=7EdVtic1i0hLDyQZ",
    "https://youtu.be/IR29DAN5vMQ?si=JLu7yjN0KxlJ7f25",
    "https://youtu.be/xRJ5QdutPaA?si=eUGg8tRb3cGc5BZg",
    "https://youtu.be/qtW8jolOStU?si=ZDKTg4Rl5CGbPnBe",
    "https://youtu.be/QL7KJqC48rg?si=lMM_u164041oPBVH",
    "https://youtu.be/Yva0bS-wuKs?si=ZGYI8VtQdcJsx6Br",
    "https://youtu.be/xmCJw944y1M?si=vx-36KSORtNsSKke",
    "https://youtu.be/tBa0uKBuUFk?si=Lq-w4Nx7DbXQMpKL",
    "https://youtu.be/RQXwpheSFKg?si=ibO-XM3hR2GnZV3g",
    "https://youtu.be/fDtp-gne1hY?si=TLdxylTsLFwBGA5R",
    "https://youtu.be/yFfP0m52qCk?si=9BtJlTy8oQljBUXT",
    "https://youtu.be/oY4HmmrlSN0?si=Ps7kqOe9UWHaTsT-",
    "https://youtu.be/Tm_nrRpC0I4?si=WYN8PH9mcM_kb3Qu",
    "https://youtu.be/qlXfyFJ1aEM?si=mOipF3Fh2pd7T3o7",
    "https://youtu.be/HbqB883qMJ0?si=1hiD8tsDpMqlyhfB",
    "https://youtu.be/lRZq29oK3RA?si=cE3Bnlpj1X22fiiK",
    "https://youtu.be/8p1sUih8vPU?si=JBiriuVMvCDNKLDy",
    "https://youtu.be/QmIpzn66zI0?si=k7vsD_tm0Bzcs8_Q",
    "https://youtu.be/EkAxa3jcmZE?si=HXPp8W2vNOXTGTox",
    "https://youtu.be/POcsQ5-Z8FI?si=S9FGnLQQxCzHnt7l",
    "https://youtu.be/ghllgDOV8uA?si=InHJ0njyfmfuxrh7",
    "https://youtu.be/ZSPAxMkKFkg?si=qQlgbN9axpjHRvrB",
    "https://youtu.be/RdegkPM4xAY?si=1BpzXgtkYiGUQEL8",
    "https://youtu.be/yNnZ8p_6hck?si=oArrfMds8n0cZ2MT",
    "https://youtu.be/lYQyNMGaTk0?si=vPk9GE0zpXNVB7sj",
    "https://youtu.be/6cPxnHfvRBM?si=pdzXuey0zDH7-Qbx",
    "https://youtu.be/tcyR8SJTDno?si=rRRv7tFUM_r05y5y",
    "https://youtu.be/PPGVYPF3YqA?si=fajoepEZShjxYJsh",
    "https://youtu.be/lYDICAQ-lfM?si=JezK9stkf2nGSQNr",
    "https://youtu.be/d1eWNoabeqE?si=ExAl3EcWy4THi1b-",
    "https://youtu.be/G-9VEHwLJko?si=COojnl5r68ivUAlw",
    "https://youtu.be/7DGhJwDqMpI?si=w4uZ7hf8ZXEfFtwL",
    "https://youtu.be/2wAW3XdBYt4?si=QIxl_Q_4fV1FKMl_",
    "https://youtu.be/0IHbz4e3BO8?si=7HpvkAMJbpetKL_E",
    "https://youtu.be/ZNq88dxpGjY?si=xG0b6OpxI-U6r8OX",
    "https://youtu.be/lVRWRr5_1DU?si=1G9PGmypIsL7i8hB",
    "https://youtu.be/EJSCmczPkko?si=w6K6Dj7obWlG9Yw2",
    "https://youtu.be/v2vcAGExS74?si=Z3PuMnuxYe_wkubZ",
    "https://youtu.be/v2vcAGExS74?si=Z3PuMnuxYe_wkubZ",
    "https://youtu.be/YrKJ2N8ZsA8?si=XNDR38EBI5JxhOk2",
    "https://youtu.be/Mmy6V8yyi6o?si=XvocwebRgWTbuU45",
    "https://youtu.be/7-_p_yKRdx4?si=URPquzqb322cGzr2",
    "https://youtu.be/F4xY__FoDzY?si=pG-oS_PlsPZWFIPh",
    "https://youtu.be/NXzemsmvX_g?si=4j7eISyAESPPUGEk",
    "https://youtu.be/uAJsHEpvz78?si=T5F36ssIpV5Tfj2t",
    "https://youtu.be/1O8f6A0K59o?si=qFJdr0Zf40kVvt49",
    "https://youtu.be/PZRUhSkJxuc?si=DDW0YWHz63aSmINa"]

bangla_urls = [
    "https://youtu.be/nDMZA5yRM0U?si=WydW4U4c0AjXE11K",
    "https://youtu.be/hWHCsysOxBk?si=BABf3xDwS8L-_0Kr",
    "https://youtu.be/ZkIaQS9rpT4?si=3YRiQW6daIvENfBu",
    "https://youtu.be/SYe-x9ZQF7o?si=FziH7dnX0qDjZePf",
    "https://youtu.be/EZ7qBDIETWQ?si=Kwq49ni4UGV1qfSZ",
    "https://youtu.be/E97X_0Y1H1s?si=MqvNA0Zz85CuP9Re",
    "https://youtu.be/i87BzWtOWEs?si=o390hAFhBA_91gvZ",
    "https://youtu.be/N756iLsiOqU?si=BpECevPU_QSzwOjX",
    "https://youtu.be/q45HaIOLeWE?si=RR3PH5oypxeOKoIB",
    "https://youtu.be/-H6OESw9Hmg?si=b6CmODY2oq0cjTIL",
    "https://youtu.be/mT7lqHT9B1g?si=xbk__ZPPmqx7lVid",
    "https://youtu.be/aDFWa40OcnQ?si=mvrCGUwG772BllHz",
    "https://youtu.be/8Ql80UCtbBg?si=pxm-j5UvtITcSImM",
    "https://youtu.be/ehuhOg9m0hw?si=uiQt86Bsba62enUb",
    "https://youtu.be/UgKlMxn8X7o?si=DTvfuclPjdLtl5GG",
    "https://youtu.be/7Nr4nWgySoU?si=o1Ati2JbehULaU-x",
    "https://youtu.be/qF2noArPaX0?si=LgwawnZJnpcuNpFC",
    "https://youtu.be/_sqHhnH2jwk?si=GnqnYY-3_BiBce3Y",
    "https://youtu.be/qsgmArlYjLg?si=JACwVlTYbkwQmKdZ",
    "https://youtu.be/o3TWnd1_Xpo?si=3IxQqDFCAQuDc9r6",
    "https://youtu.be/uxqLbkvdmsI?si=cYhL-6Sg9ySzIKqM",
    "https://youtu.be/O6HFQyD7rCI?si=dLcFB2wWZdS5GHgp",
    "https://youtu.be/CMF4gZEYLG8?si=WmChPAinMdmFVWW8",
    "https://youtu.be/y-exkDdFJYk?si=Q99mn--BxNtQk-PB",
    "https://youtu.be/hb7R9pu5I0c?si=i728wtbO8pSOq4S3",
    "https://youtu.be/08SDuIhlQlo?si=BsAY_dOqZdFj8k8m",
    "https://youtu.be/FsmLVBA0jk0?si=MdEZxiAaSw5EjV4H",
    "https://youtu.be/cBwqyjk7mdI?si=hMD-e-jRrsgkpQNO",
    "https://youtu.be/MGed3BUHJMU?si=TjqTY4JGTmuicFeh",
    "https://youtu.be/mu7Ilt2f29I?si=uASHY9yPSOUl5NmK",
    "https://youtu.be/-24zBDFTG28?si=FoL7ElApcKZ3tmjQ"]

import subprocess

def download_audio(url, out_dir):
    cmd = [
        "yt-dlp",
        "-x",
        "--audio-format", "wav",
        "-o", f"{out_dir}/%(title)s.%(ext)s",
        url
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    print(result.stdout)
    print(result.stderr)

for url in english_urls:
    download_audio(url, "audio_data/english")

for url in bangla_urls:
    download_audio(url, "audio_data/bangla")

import librosa
import numpy as np
from tqdm import tqdm

def extract_mfcc(file_path):
    y, sr = librosa.load(file_path, duration=30, sr=22050)
    mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=40)
    return np.mean(mfcc, axis=1).tolist()

data = []

for lang in ["english", "bangla"]:
    folder = f"audio_data/{lang}"
    for file in tqdm(os.listdir(folder)):
        if file.endswith(".wav"):
            try:
                path = folder + "/" + file
                mfcc = extract_mfcc(path)
                data.append({
                    "song": file[:-4],
                    "language": lang,
                    "mfcc": mfcc
                })
            except Exception as e:
                print("Failed:", file, e)

import pandas as pd

df_audio = pd.DataFrame(data)
df_audio.to_csv("audio_mfcc_dataset.csv", index=False)
df_audio